# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 719e675952d9e906950cc778debb71efcc2f78af2d6f42475ef473ed02a7a13e99e3b08ea821e040ffadcd795d7084f2e789802cbd1fc9d19f3f4a01465dc0a9

test:
  secret_key_base: 619fdfc922cc713bdea615deacec8ffbd94c36942a83e37428ba40a8511d48578283079980196857e69335f1a4bfc0e5a224f77c5c8e286b8c8b7077b72d940e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
